apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-app-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-v3
  template:
    metadata:
      labels:
        app: grade-v3
    spec:
      containers:
      - name: grade-app
        image: yourdockerhub/grade-app:v3
        ports:
        - containerPort: 3000
